substitutions:
  name: electra-rc3-remote
  friendly_name: Electra RC3 IR Remote

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp8266:
  board: d1_mini

external_components:
  # https://github.com/Pristavkin/esphome_electra_rc3
  - source: github://Pristavkin/esphome_electra_rc3@main
    components: [ electra_rc3 ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

ota:
  password: !secret ota_password

web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

preferences:
  flash_write_interval: 180min
             
remote_transmitter:
  pin: 
    number: D3
  carrier_duty_percent: 50%

climate:
  - platform: electra_rc3
    name: "Electra AC"
    sensor: "${name}_temperature"
    